name: Docker-hub

on:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Login to Docker
       uses: docker/login-action@v3.3.0
       with:
        username: ${{secrets.DOCKER_U}}
        password: ${{secrets.DOCKER_P}}

     - name: Build docker image
       run: |
        docker build -t ${{secrets.DOCKER_P}}/getting-started:v3 .
        docker tag $DOCKER_IMAGE:${{github.sha}} $DOCKER_IMAGE:v3
       
     - name: Push docker image
       run: |
        docker push ${{secrets.DOCKER_P}}/getting-started:v3     

    
